spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root123
    url: jdbc:postgresql://localhost:5432/snap_books
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
